
Convolution of image and kernel using numpy 

In [1]:
import numpy as np

In [2]:
def conv2D(image, kernel, padding=0, strides=1):
    # Cross Correlation
    kernel = np.flipud(np.fliplr(kernel))

    # Gather Shapes of Kernel + Image + Padding
    xKernShape = kernel.shape[0]
    yKernShape = kernel.shape[1]
    xImgShape = image.shape[0]
    yImgShape = image.shape[1]

    # Shape of Output Convolution
    xOutput = int(((xImgShape - xKernShape + 2 * padding) / strides) + 1)
    yOutput = int(((yImgShape - yKernShape + 2 * padding) / strides) + 1)
    output = np.zeros((xOutput, yOutput))

    # Apply Equal Padding to All Sides
    if padding != 0:
        imagePadded = np.zeros((image.shape[0] + padding*2, image.shape[1] + padding*2))
        imagePadded[int(padding):int(-1 * padding), int(padding):int(-1 * padding)] = image
        print(imagePadded)
    else:
        imagePadded = image

    # Iterate through image
    for y in range(image.shape[1]):
        # Exit Convolution
        if y > image.shape[1] - yKernShape:
            break
        # Only Convolve if y has gone down by the specified Strides
        if y % strides == 0:
            for x in range(image.shape[0]):
                # Go to next row once kernel is out of bounds
                if x > image.shape[0] - xKernShape:
                    break
                try:
                    # Only Convolve if x has moved by the specified Strides
                    if x % strides == 0:
                        output[x, y] = (kernel * imagePadded[x: x + xKernShape, y: y + yKernShape]).sum()
                except:
                    break

    return output

In [3]:
kernel = [[-1, 0, 1],
          [-1, 0, 1],
          [-1, 0, 1]]
image = np.random.random((5,5)) 
image = np.around(image, decimals = 2)
image = np.pad(image, pad_width=1)
print(f"image: {image}")
output = conv2D(image, kernel)
print(f"output: {output}")

image: [[0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.53 0.84 0.56 0.71 0.88 0.  ]
 [0.   0.64 0.96 0.47 0.21 0.04 0.  ]
 [0.   0.2  0.12 0.68 0.83 0.8  0.  ]
 [0.   0.95 0.48 0.53 0.99 0.22 0.  ]
 [0.   0.16 0.89 0.53 0.56 0.73 0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]]
output: [[-1.8   0.14  0.88  0.11  0.92]
 [-1.92 -0.34  0.17 -0.01  1.75]
 [-1.56  0.11 -0.47  0.62  2.03]
 [-1.49 -0.43 -0.89 -0.01  2.38]
 [-1.37  0.05 -0.18  0.11  1.55]]
